### PR TITLE
Pancake Tuesday 2024

### PR DESCRIPTION
**Pull request by byemc**

### CODE REVIEW

**Comment by nyakase** [comment]
Amy is eating all the projects (I think), so I can't guarantee I will git pull this immediately.

I'll merge it though.

**Comment by nyakase** [comment]
Amy is eating all the projects (I think), so I can't guarantee I will fit pull this immediately.

I'll merge it though.

**Comment by nyakase** [comment]
Amy is eating all the projects (I think), so I can't guarantee I will fit pull this immediately.

I'll merge it though.can't guarantee I will fit pull this immediately.

I'll merge it though.

**Comment by byemc** [comment]
> Amy is eating all the projects (I think), so I can't guarantee I will fit pull this immediately.
> 
> I'll merge it though.

me when the twice

**Comment by emilianya** [comment]
project eating is over

**Comment by byemc** [comment]
why is project eat

**Comment by nyakase** [comment]
Amy is eating all the projects (I think), so I can't guarantee I will fit pull this immediately.

I'll merge it though.can't guarantee I will fit pull this immediately.

I'll merge it though. help how do I merge

**Comment by emilianya** [comment]
i was migrating stuff to a new database

**Comment by byemc** [comment]
fair

**Comment by emilianya** [comment]
backups are nice

**Comment by emilianya** [comment]
we didnt have them before now

**Comment by nyakase** [comment]
"head brance was modified" i dontvtcareeeeee

**Comment by nyakase** [comment]
"head brance was modified" i dontvtcareeeeee

**Comment by nyakase** [comment]
"head brance was modified" i dontvtcareeeeee

**Comment by byemc** [comment]
i'm trying to migrate my mastodon instance

**Comment by nyakase** [comment]
this mobile app is a disaster

**Comment by byemc** [comment]
it's going bad

**Comment by emilianya** [comment]
wel ldone you merged it with only a billion duplicate comments

**Comment by byemc** [comment]
oh it's finished copying

**Comment by nyakase** [comment]
No network connection

Wtf di you mean network connection - [ ] I'm right here

**Comment by byemc** [comment]
am i silly i sign my commits

**Comment by byemc** [comment]
like, with an SSH key

**Comment by nyakase** [comment]
What is the point of doing that

**Comment by byemc** [comment]
no idea

**Comment by nyakase** [comment]
Fuck i locked it too late

**Comment by nyakase** [comment]
U was going to stop you from aansweing

**Comment by emilianya** [comment]
image
you are flooding my inbox

**Comment by nyakase** [comment]
Teehee :3

**Pull request merged**
