### PR TITLE
Byecorps day

### PR DESCRIPTION
**Pull request by byemc**
national holidy

(ignore the other commits i think my fork is broken)

### CODE REVIEW

**Comment by emilianya** [comment]
not even gonna look at changes

**Comment by byemc** [comment]
i sure hope dates are in the format MM-DDSent from my Apple WatchOn 31 Oct 2023, at 18:41, Emilia ***@***.***> wrote:
not even gonna look at changes

**Comment by emilianya** [comment]
this reply looks quite broken but thanks i definitely dont remember but i would expect not but who knows

**Comment by emilianya** [comment]
yeah i checked its DD-MM

**Comment by emilianya** [comment]
i think

**Comment by nyakase** [comment]
Sent from my desktop computer

**Comment by nyakase** [comment]
Also yeah dates are DD-MM because you got angy when they were MM-DD even though it made more sense for it to be like that name sorting wise

**Pull request merged**
